user settings:
  accepted tags:
    - heavy metal
    - alternative metal
    - funk metal
    - nu metal
    - rap metal
    - avant-garde metal
    - black metal
    - ambient black metal
    - blackened heavy metal
    - blackened screamo
    - blackgaze
    - black'n'Roll
    - depressive suicidal black metal
    - NSBM
    - post-black metal
    - red and anarchist black metal
    - symphonic black metal
    - viking metal
    - war metal
    - christian metal
    - unblack metal
    - crust punk
    - blackened crust
    - death metal
    - blackened death metal
    - death 'n' roll
    - melodic death metal
    - technical death metal
    - symphonic death metal
    - doom metal
    - death-doom
    - drone metal
    - funeral doom
    - sludge metal
    - stoner metal
    - extreme metal
    - folk metal
    - celtic metal
    - pirate metal
    - pagan metal
    - glam metal
    - hair metal
    - pop metal
    - gothic metal
    - grindcore
    - deathgrind
    - goregrind
    - Pornogrind
    - electrogrind
    - grunge
    - Industrial metal
    - Industrial death metal
    - Industrial black metal
    - kawaii metal
    - latin metal
    - metalcore
    - melodic metal
    - deathcore
    - mathcore
    - electronicore
    - synthcore
    - trancecore
    - nu metalcore
    - nu metal revival
    - new nu metal
    - progressive metalcore
    - technical metalcore
    - ambient metalcore
    - neoclassical metal
    - shred metal
    - neue Deutsche Härte
    - post-metal
    - power metal
    - progressive metal
    - djent
    - space metal
    - speed metal
    - symphonic metal
    - thrash metal
    - crossover thrash
    - ghroove metal
    - teutonic thrash metal
    - traditional heavy metal
    - New wave of British heavy metal
    - NWOBHM
    - New wave of American heavy metal
    - NWOAHM
    - New wave of traditional heavy metal
    - NWOTHM